name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"  # Updated to support null safety

dependencies:
  flutter:
    sdk: flutter

  modal_progress_hud_nsn: ^0.3.0
  firebase_core: ^3.7.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.2
  animated_text_kit: ^4.2.1





  cupertino_icons: ^1.0.4  # Latest version as of now

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
